### ISSUE TITLE
[BUG]: Create env file 

### ISSUE THREAD

**Issue by artemis-i-guess** [artemis-i-guess/ArteRed#1]
Create env file to remove username and password from code in `reddit.py `

 Also do the same for Bot token in `main.py` . line 28

**Comment by DugarRishab** [comment]
I would like to contribute to this issue. Can you please assign me?

**Comment by artemis-i-guess** [comment]
> I would like to contribute to this issue. Can you please assign me?

Yes @DugarRishab, I have assigned you .
